translator:
  type: openai
  model: gpt-4o
  openai_api_key: YOUR-KEY-GOES-HERE

layout:
  type: 'dit'
  device: 'cuda'
  dpi: 200

ocr:
  type: 'paddle'
  device: 'cuda'

font:
  type: 'nanum'  # use 'nanum' for NanumMyeongjo
  dpi: 200       # base dpi used to scale fonts
